$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
     loop:false,
     margin:30,
     nav:true,
     responsive:{
         0:{
             items:1
         },
         600:{
             items:2
         },
         1000:{
             items:3
         },
         1200:{
             items:4
         }
     }
 })
});
